### PR TITLE
Fix for uncentered BoundingBoxes

### LINKED ISSUE #2: Non-centered Bounding boxes not respected
Hello,

1. noice crate, thank you for the work!
2. non-centered boxes are not handled correctly internally

The Voronoi-algorithm for example uses [`BoundingBox::is_inside()`](https://github.com/andreesteve/voronoice/blob/master/src/bounding_box.rs#L87)
```rust
is_inside = point.x.abs() <= self.top_right.x && point.y.abs() <= self.top_right.y
```
which only works for centered boxes.

Similarily [`which_edge()`](https://github.com/andreesteve/voronoice/blob/master/src/bounding_box.rs#L100)
```rust
if point.y == self.top_right.y {
    // top
    BoundingBoxTopBottomEdge::Top
} else if point.y == -self.top_right.y {
    BoundingBoxTopBottomEdge::Bottom
} else {
    BoundingBoxTopBottomEdge::None
}
```
relies on mirrored coordinates around the origin `(0,0)`
```rust
point.y == -self.top_right.y
```
---
The simplest solution would be to add a private `centered_bounding_box`-variable to the VoronoiBuilder. 
1. Center arbitrary `bounding_box` by subtracting `BoundingBox.center()` from every `site`
2. Use this centered `centered_bounding_box` in all calculations (which is the current working state)
3. Reapply `shift` back to every obtained `vertex`/`centerpoint`

However, this is problematic, if users can access the algorithm directly, without using VoronoiBuilder, because they could supply noncentered boxes instead which results in something like this:
Voronoi_problems
25 different Voronoi-Diagrams with different Bounding boxes. 
The blue cross is the world origin, 
and the red dots in the 3 quadrants (right-up, right-down, left-down) are sites for which no Voronoi-Diagram could be generated

### PR DESCRIPTION
**Pull request by Telzhaak**
Supposedly fixes #2 

This commit changes the algorithm to not rely on mirrored coordinates, instead calculating `left` and `bottom` from the `BoundingBox` and checking for coordinates to be in range `bottom <= y <= top` and `left <= x <= right`. I chose not to rely on `un-shift -> voronoi -> re-shift`, since this could cause confusion for users.

---

The new output looks okay at first glance, but the `BoundingBox` Corners (e.g. top-left Voronoi-Diagram, upper right corner) are still a little broken. Haven't figured out why, yet.
Voronoi_fix__corners_broken

---

Benchmark Comparison "large_input_benchmark":

||100.000|1.000.000|5.000.000|10.000.000|
|---|---|---|---|---|
|Fix|28.814 ms|412.98 ms|2.4891 s|5.3512 s|
|Master|29.228 ms|418.78 ms|2.4628 s|5.3161 s|

### CODE REVIEW

**Comment by Telzhaak** [comment]
After some testing, the broken corner cells were already present in the master-branch. 
So this PR "could" be seen as `ready to merge`.

I'll try to fix the corners over the weekend

**Comment by Telzhaak** [comment]
Opened new issue #4 for the corner-problem, as it is not related with any of the changes made here

**Comment by andreesteve** [comment]
@Telzhaak - thanks for the PR and reporting the issues! I started taking a look at the code and looks good.
Thanks for adding the benchmark results, I was curious on that - but looks like no measurable to minimal impact.

File: src/bounding_box.rs [hunk 1]
```diff
@@ -84,32 +85,44 @@ impl BoundingBox {
...
+        horizonal_ok && vertical_ok
     }
 
     // /// Same as inside, but return false if point is on the box edge.
-    // #[inline]
-    // pub fn is_exclusively_inside(&self, point: &Point) -> bool {
-    //     point.x.abs() < self.top_right.x && point.y.abs() < self.top_right.y
-    // }
+    #[inline]
+    pub fn is_exclusively_inside(&self, point: &Point) -> bool {
```
Comment (andreesteve) [inline src/bounding_box.rs:97]: I forgot I had left this commented out. I was debating with myself whether I should keep the BoundingBox API public, as that was not the main goal of the library. Do you see a use case to expose it?

**Review by andreesteve — APPROVED** [review]
Can I suggest adding a unit test for the case when the bounding box center isn't the origin? This will help make sure this scenario doesn't regress in the future. Thanks!

File: src/bounding_box.rs (hunk 1 above)
Comment (Telzhaak) [reply src/bounding_box.rs:97]: I would probably keep part of this API public, up to including `which_edge()`, such that users can iterate over their points (or new ones) to deal with special cases such as edges. And also expose both the original and relaxed sites, like in [`Voronoi.sites()`](https://github.com/andreesteve/voronoice/blob/9df72656ed73f7c5541d390e27d082af0c6361a2/src/lib.rs#L178)

This _could_ be used to stitch together neighboring Voronoi-diagrams or other forms of polygon-meshes ( e.g. infinite world generation in games, 2d meshing in FEM/CAM with contact-materials [this might actually require only relaxing `exclusively_inside` points]).

The rest of the function, `intersect_line()`, `project_ray()`, `project_ray_closest()` and `order_points_on_ray`, probably have no use outside of the diagram-generation and can be hidden

Comment (Telzhaak) [reply src/bounding_box.rs:97]: And sure, I'll write up a few unit tests for this tomorrow!

**Comment by Telzhaak** [comment]
Short update: I added a UnitTest for the BoundingBox, but noticed that one of my changes results in a previously fine Unittest to fail:
```
---- cell_builder::test::extend_and_close_hull_test stdout ----
thread 'cell_builder::test::extend_and_close_hull_test' panicked at 'assertion failed: `(left == right)`
  left: `[32.75, -15.5]`,
 right: `[7.905417527999327, -3.0777087639996634]`:
Invalid vertex for position 1. Expected cell vertices [
    [0.5, 0.625],
    [32.75, -15.5],
    [0.5, 33],
], found [
    [0.5, 0.625],
    [7.905417527999327, -3.0777087639996634],
    [0.5, 9],
]. First cell', src\cell_builder.rs:513:13
```
I'm currently investigating the reason for that. It broke with the previous `extend_vector normalized orthogonal` commit.
Most likely its the hardcoded, expected values, that are now outdated (depending on how you calculated them back when you implemented this test).

File: src/bounding_box.rs (hunk 1 above)
Comment (andreesteve) [reply src/bounding_box.rs:97]: Thank you! I agree it makes sense to keep the ```which_edge``` public.

**Comment by Telzhaak** [comment]
Sry, I'm currently busy moving, and I forgot to get back at this.

It is indeed due to the expected values being outdated. 
Normalizing the `orthogonal`, and changing the `scale` factor to be the more easily computed as `width+height` of course changes where the extended vertices end up

Due to these changes, it is also very very difficult to find "pretty" numbers for tests.
I changed the tested triangle to be 
```
(-0.5,  1.0)
(-1.5, -1.0)
( 0.5, -1.0)
```

----
## According to my hand-math:
circumcenter `c = (-0.5, -0.25)`
new `scale = width + height = 4 + 4 = 8`
angles with `+x`-axis as reference
```rust
e1angle = 270° - atan(-1/-2) = 243.435°
e2angle = 0°
e3angle = 180° - atan(2/1) = 116.565°
```
### The following vertices represent a rough estimate of where the extended vertice should end up
Instead of extending the half-edge-intersection point, the circumcenter is extended:
```rust
exv1.x = c.x + scale * cos(e1angle - 90°) = -0.5 + 8. * cos(153.435°) = -7.655
exv1.y = c.y + scale * sin(e1angle - 90°) = -0.25 + 8. * sin(153.453°) = 3.328

exv2.x = c.x + scale * cos(e2angle - 90°) = -0.5 + 8. * cos(-90°) = -0.5
exv2.y = c.y + scale * sin(e2angle - 90°) = -0.25 + 8. * sin(-90°) = -8.25

exv3.x = c.x + scale * cos(e3angle - 90°) = -0.5 + 8. * cos(26.565°) = 6.655
exv3.y = c.y + scale * sin(e3angle - 90°) = -0.25 + 8. * sin(26.565°) = 3.328
```

### The following vertices are calculated by the code:
1. `(7.865633420552356, 2.8089875327071336)`
2. `(8.155417527999326, 3.5777087639996634)`
3. `(-0.5, -9)` <-
The proximity of each calculated point to its hand-estimated position is an indicator, that the expected test-values are correct. This is confirmed by the third point, whose mid-edge intersection point is trivial to find at `(-0.5, -1.0)`. Extending this by `scale` in `-90°`-direction leads to exactly this value.

---

Thus, this PR finished its scope and can be merged
